### ISSUE TITLE
Create and publish guidelines

### ISSUE THREAD

**Issue by sajoy** [wwcodeportland/wwc-website#2]
To address process for:
- PM using GitHub (or alternative)
- Work flow: build process, dev environment set up, claiming TODO's
- Git flow: forking, branching, PR's, code review
- Pairing
- editorconfig, linter rules

To be published in README.md file

**Comment by sajoy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Outline development/contribution process in repo README.md](https://trello.com/c/dyh8ktIo/94-outline-development-contribution-process-in-repo-readmemd)

**Comment by morganpdx** [comment]
README.md and CONTRIBUTING.md added.
